version: '3.4'
services:
  acme-aggregator-share:
    #image: alfresco-share-acme-aggregator:development
    image: acme-aggregator-share-docker:latest
    #build:
      #dockerfile: ./Dockerfile
      #context: ../../../acme-aggregator-share-docker/target
    environment:
      CATALINA_OPTS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=0.0.0.0:8888"
      REPO_HOST: acme-aggregator-acs
      REPO_PORT: 8080
    ports:
      - "${share.port}:8080"
      - "${share.debug.port}:8888"
  acme-aggregator-acs:
    #image: alfresco-content-services-acme-aggregator:development
    image: acme-aggregator-platform-docker:latest
      #build:
    #  dockerfile: ./Dockerfile
    #  context: ../../../acme-aggregator-platform-docker/target
    environment:
      JAVA_TOOL_OPTIONS: "${keystore.settings}"
      JAVA_OPTS: "
        -Dsolr.secureComms=secret
        -Dsolr.sharedSecret=secret
        -Dmessaging.broker.url=\"failover:(nio://acme-aggregator-activemq:61616)?timeout=3000&jms.useCompression=true\"
        "
      CATALINA_OPTS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=0.0.0.0:8888"
    ports:
      - "${acs.port}:8080"
      - "${acs.debug.port}:8888"
    volumes:
      - acme-aggregator-acs-volume:/usr/local/tomcat/alf_data
    depends_on:
      - acme-aggregator-postgres
  acme-aggregator-postgres:
    image: postgres:9.6
    environment:
      POSTGRES_DB: alfresco
      POSTGRES_USER: alfresco
      POSTGRES_PASSWORD: alfresco
    command: postgres -c max_connections=300 -c log_min_messages=LOG
    ports:
      - "${postgres.port}:5432"
    volumes:
      - acme-aggregator-db-volume:/var/lib/postgresql/data
  acme-aggregator-ass:
    image: alfresco/alfresco-search-services:2.0.3
    environment:
      SOLR_ALFRESCO_HOST: acme-aggregator-acs
      SOLR_ALFRESCO_PORT: 8080
      SOLR_SOLR_HOST: acme-aggregator-ass
      SOLR_SOLR_PORT: 8983
      SOLR_CREATE_ALFRESCO_DEFAULTS: alfresco,archive
      ALFRESCO_SECURE_COMMS: "secret"
      JAVA_TOOL_OPTIONS: "-Dalfresco.secureComms.secret=secret"
    ports:
      - "8983:8983"
    volumes:
      - acme-aggregator-ass-volume:/opt/alfresco-search-services/contentstore
      - acme-aggregator-ass-volume:/opt/alfresco-search-services/data
  acme-aggregator-activemq:
      image: alfresco/alfresco-activemq:5.16.1
      mem_limit: 1g
      ports:
        - 8161:8161 # Web Console
        - 5672:5672 # AMQP
        - 61616:61616 # OpenWire
        - 61613:61613 # STOMP

volumes:
  acme-aggregator-acs-volume:
    external: true
  acme-aggregator-db-volume:
    external: true
  acme-aggregator-ass-volume:
    external: true
